### ISSUE TITLE
Local strategy

### ISSUE THREAD

**Issue by seminice** [dai-shi/social-cms-backend#10]
Example usage for local strategy? email and password.

**Comment by dai-shi** [comment]
Here's the example.

    it('should create a new user', function(done) {
      request.post('http://localhost:' + port + '/adduser/local', {
        json: true,
        form: {
          username: 'user001',
          password: 'password001'
        }
      }, function(error, response) {
        assert.equal(response.statusCode, 200);
        assert.ok(response.body.user_id);
        done();
      });
    });

    it('should login as a user', function(done) {
      request.post('http://localhost:' + port + '/login/local', {
        json: true,
        form: {
          username: 'user001',
          password: 'password001'
        }
      }, function(error, response) {
        assert.equal(response.statusCode, 200);
        assert.ok(response.body.user_id);
        done();
      });
    });

As you might guess, the main purpose of local strategy is testing. But it's up to you how to use it.

**Comment by seminice** [comment]
I know, I read the tests , its just that I was looking for something to try on quickly and debug since I have no facebook account.
Btw consider having that as the main example since you are providing a mean for creating one's own social media its not a common sense to use another social media to authenticate as MAIN EXAMPLE .. just saying :).

**Comment by dai-shi** [comment]
Oh, I see what you mean now. For such a closed environment, I would suggest the DIGEST auth. But, the issue is that it is not very common and   not very easy to add a new user. So, the local strategy might be only an option. Hmm.

**Comment by dai-shi** [comment]
Added "auth-local" example, which is rough though.
