### ISSUE TITLE
Following members stored as String

### ISSUE THREAD

**Issue by chattes** [dai-shi/social-cms-backend#20]
Hi
When I send a POST with Following members.
The members are getting stored in the database as 
"following":{
"user": "1"
}
Since the data is getting sent as AJAX JSON body.

But when I query the /inbox endpoint it queries for [user: 1] and does not return the correct posts. You can try sending an AJAX request and check once for following

**Comment by dai-shi** [comment]
JSON supports numbers, so can you simply send it like the following?
```
  "following": {
    "user": 1
  }
```

**Comment by chattes** [comment]
I am sending the data as number only but it is getting saved as a string in the database. I will retry and let you know soon.

**Comment by chattes** [comment]
Issue got resolved , I had to JSON.stringify() before sending the body.
