### ISSUE TITLE
Need out of the box instructions. 

### ISSUE THREAD

**Issue by temecom** [dai-shi/social-cms-backend#8]
The service fails to start out of the box with: 

../node_modules/social-cms-backend/lib/authentication/auth_facebook.js:131
    throw new Error('facebook_app_id or facebook_app_secret is not specified.'
          ^
Error: facebook_app_id or facebook_app_secret is not specified.

There appears to be some environmental configuration that is necessary. 
FACE_BOOK_APP_ID 
FACE_BOOK_APP_SECRET

Probably in explained in the facebook node but would be handy here.

**Comment by dai-shi** [comment]
Thanks. I would add a line about the facebook configuration.

**Comment by dai-shi** [comment]
Does it work for you?

**Comment by temecom** [comment]
I got a little further now. It doesn't error out and connects to Mongo but GET /posts returns: 

unable to query objects: Error: no VIEW_OBJECTS permission

seems like a mongo permissions thing??

Is there a system mongo user?

**Comment by dai-shi** [comment]
Oh, good point. Thanks for pointing it out.

The default permission model is to allow all authenticated users to view objects, which means users must login at first.
To login by facebook, redirect to /login/facebook, and to get login user information GET /users/myself.
(We need instructions in README, obviously.)

There's no system user by default.

**Comment by temecom** [comment]
Daishi,

I have my Facebook app authentication setup and working through a 
browser but don't seem to be able to get the social-cms-backend to 
recognize the login. I have the FACEBOOK_APP_ID and FACEBOOK_APP_SECRET 
assigned to the correct values but there is something missing and no 
output to tell me what it is.

I will try debugging, but if there is something obvious that you can 
remember that needs to be done it would be very helpful.

Thanks

Chris

**Comment by dai-shi** [comment]
Thanks for trying it out.

Do you get redirected back to the site after you sign in to Facebook? If not, callback url may not be working.

**Comment by dai-shi** [comment]
Hi, I updated the example up to date. <https://github.com/dai-shi/twitter-clone-sample>
Please give it a try.

**Comment by temecom** [comment]
I am logged into Facebook from an app served by the node but when I enter: 

localhost:3000/users

 in the browser I always get: 

 "unable to query objects: Error: no VIEW_OBJECTS permission"

There is something else missing in the API documentation... the authentication sequence and the headers(s) that have to be set in the browser after authentication. User perhaps? I've tried tracing the network calls and looking at the cookies in the sample app but nothing jumps out.

Thanks - this is a great little package.

**Comment by dai-shi** [comment]
Isn't it possible to share your minimal code to reproduce the issue?

**Comment by temecom** [comment]
The missing piece of the puzzle is a link on the web page: 

 <a href="/login/facebook" >Login</a>

This hooks into the authentication module using the configured facebook method and accepts the OAuth token for subsequent use.

**Comment by dai-shi** [comment]
Nice to hear that. I will definitely add it to the readme.

**Comment by dai-shi** [comment]
Hope it makes sense.
