### ISSUE TITLE
Problems running on node v0.12

### ISSUE THREAD

**Issue by temecom** [dai-shi/social-cms-backend#9]
Runs fine on v0.10 but when I switch to v0.12 I get: 

[Error: Module did not self-register.]
js-bson: Failed to load c++ bson extension, using pure JS version

The service does not respond to any requests. Probably caused by the Error.

**Comment by dai-shi** [comment]
Thanks for reporting this. Confirmed that npm test doesn't pass with node-v0.12.

**Comment by dai-shi** [comment]
Hm, actually it is ok. The npm test fails only around socket.io.
I'm certain that one of my apps using SCB is running with node-v0.12.

**Comment by dai-shi** [comment]
I ran <https://github.com/dai-shi/twitter-clone-sample> with node-v0.12 just fine.

**Comment by dai-shi** [comment]
I just opened the issue about npm test with node-v0.12, so closing this. Please reopen this issue if you still have the issue.
